apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
{{- if .Values.main.annotations }}
  annotations:
{{ toYaml .Values.main.annotations | indent 4 }}
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.main.type }}
  ports:
  - port: {{ .Values.main.port }}
    protocol: TCP
    name: http
  selector:
    app: {{ template "fullname" . }}
    release: "{{ .Release.Name }}"
